apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micro-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: micro.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /go
        pathType: Prefix
        backend:
          service:
            name: go-service
            port:
              number: 8081
      - path: /python
        pathType: Prefix
        backend:
          service:
            name: python-service
            port:
              number: 8082
      - path: /node
        pathType: Prefix
        backend:
          service:
            name: nodejs-service
            port:
              number: 8083
      - path: /java
        pathType: Prefix
        backend:
          service:
            name: java-service
            port:
              number: 8084
